### ISSUE TITLE
Batch processor - new names not being added to backbone.

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#29]
CLicking new names appears to assign a wfo ID to the record in the table held in the Batch processor, but the names/id doesnt appear in the front end editor. When your re run matching it doesnt find a record of the name with id.

Cyrtandra kinhoi is in the GTS_trees not found 
Cyrtandra kinhoi is in the Gesner table, already added as a new name with id wfo-1000000843

**Comment by rogerhyam** [comment]
I believe I have fixed this and the code is on the sandbox server. I've added a screen so that after you click "create name" you will be shown a confirmation and an opportunity to look at name in the Rhakhis UI.

Because I have change the mechanism used it will now refuse to create new names that are homonyms (same name string and any author string). In these cases you will need to create the name through the normal UI and confirm you are adding a homonym by ticking the boxes.

This is not on the live site yet as it comes with a bunch of other changes we should check before deployment.
